<h1 style="color:#34ff00">REPASO PY</h1>
<p style="color:#959b99">Nombre: Sigcho Cueva Geordy Andres</p>

<h4 style="color:#34ff00"> Importar biblioteca Numpy</h4>

In [1]:
import numpy as np

<h4 style="color:#34ff00"> Crear un array unidimensional</h4>

In [25]:
MiArray = np.array([2, 4, 6, 8, 10, 12])

<h4 style="color:#34ff00"> Acceder a elementos del array</h4>

In [4]:
print(MiArray[2])

6


<h4 style="color:#34ff00"> Operaciones con arrays</h4>

In [26]:
MiArray += 2
print(MiArray)

[ 4  6  8 10 12 14]


<h4 style="color:#34ff00"> Crear un array bidimensional</h4>


In [43]:
MiMatriz = np.array([[2, 4, 6, 8],[1, 3, 5, 7]])
print(MiMatriz)

[[2 4 6 8]
 [1 3 5 7]]


<h4 style="color:#34ff00"> Acceder elementos de la matriz</h4>


In [37]:
print(MiMatriz[1,2]) # El primer Num es la fila y el segundo Num es la columna

5


<h4 style="color:#34ff00"> Eliminar por indice columna</h4>


In [44]:
MiMatriz = np.delete(MiMatriz, 1, axis=1) #Indicamos que empiece por el indice 1
# Luego indicamos en axis = 1 que significa que trabajaremos con columnas y 0 con filas
print(MiMatriz)

[[2 6 8]
 [1 5 7]]


<h4 style="color:#34ff00"> Eliminar por indice fila</h4>


In [45]:
MiMatriz = np.delete(MiMatriz, 1, axis=0) #Indicamos que empiece por el indice 1
# Luego indicamos en axis = 1 que significa que trabajaremos con columnas y 0 con filas
print(MiMatriz)

[[2 6 8]]


<h4 style="color:#34ff00"> Reemplazar un valor</h4>


In [46]:
MiMatriz[MiMatriz == 6] = 2002
print(MiMatriz)

ValueError: invalid literal for int() with base 10: 'Cambiado'